version: '2'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: couchdb
    volumes:
      - /var/db/:/usr/local/var/lib/couchdb
    ports:
      - "5984:5984"
