FROM ruby
WORKDIR /test
# Install phantomjs
RUN \
  wget -q --no-check-certificate -O /tmp/phantomjs.tar.bz2 \
  https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
  tar -xjf /tmp/phantomjs.tar.bz2 -C /tmp && \
  rm -f /tmp/phantomjs.tar.bz2 && \
  mv /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs
COPY Gemfile /test/
COPY Gemfile.lock /test/
RUN bundle install
CMD bundle exec cucumber
ADD . /test
